import { Inter } from '@next/font/google'
import styles from './layout.module.css'
// import { Box } from '@mui/system'
import { Table } from '../Table/table'
import { Title} from '../Title/title'
import { Box } from '@mui/system'
import Head from 'next/head'
// const inter = Inter({ subsets: ['latin'] })



export  function Layout({children}) {
  
  return (
    <>
        <Head>
            <title>kings cup</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/card-icon.svg" />
        </Head>
        <main className={styles.app}>
            <Box className='layout'>
                <Title/>
                <Table>
                    {children}
                </Table>
            </Box>
            
        </main>
    </>
    
  )
}